# Generated by Django 6.0.3 on 2026-03-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
