# Generated by Django 6.0.3 on 2026-03-26 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyPaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('emergency_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='loans.emergencyloan')),
            ],
        ),
    ]
