# Generated by Django 6.0.3 on 2026-03-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_emergencypaymentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyloan',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
