# Generated by Django 6.0.3 on 2026-03-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_customer_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='start_date',
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loans.customer')),
            ],
        ),
    ]
