# Generated by Django 6.0.3 on 2026-03-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_paymentschedule_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencypaymentschedule',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
