# Generated by Django 6.0.3 on 2026-03-26 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_emergencyloan_remaining_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencypaymentschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencypaymentschedule',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='emergencypaymentschedule',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
