# Generated by Django 6.0.3 on 2026-03-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_emergencypaymentschedule_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencypaymentschedule',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
