# Generated by Django 6.0.3 on 2026-03-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_emergencypaymentschedule_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyloan',
            name='principal_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
