# Generated by Django 6.0.3 on 2026-03-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_interest_rate_alter_loan_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_type',
            field=models.CharField(choices=[('percent', 'Percentage (%)'), ('amount', 'Fixed Amount')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
