# Generated by Django 6.0.3 on 2026-03-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_emergencypaymentschedule_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
    ]
