# Generated by Django 6.0.3 on 2026-03-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_emergencyloan_principal_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyloan',
            name='principal_balance',
        ),
        migrations.RemoveField(
            model_name='emergencypaymentschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emergencypaymentschedule',
            name='principal_paid',
        ),
    ]
