# Generated by Django 6.0.3 on 2026-03-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_remove_emergencyloan_principal_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyloan',
            old_name='remaining_balance',
            new_name='remaining_principal',
        ),
        migrations.AddField(
            model_name='emergencypaymentschedule',
            name='payment_type',
            field=models.CharField(choices=[('interest', 'Interest'), ('principal', 'Principal')], default='interest', max_length=10),
        ),
        migrations.AlterField(
            model_name='emergencypaymentschedule',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
