# Generated by Django 6.0.3 on 2026-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_payment_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
