# Generated by Django 6.0.3 on 2026-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_remove_loan_created_at_remove_loan_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
