# Generated by Django 6.0.3 on 2026-04-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_loan_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='payment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('semi_monthly', 'Semi_monthly'), ('monthly', 'Monthly')], default='daily', max_length=15),
        ),
    ]
