# Generated by Django 6.0.3 on 2026-04-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_alter_loan_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
