# Generated by Django 6.0.3 on 2026-04-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_paymentschedule_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencypaymentschedule',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
