# Generated by Django 6.0.3 on 2026-04-11 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_emergencypaymentschedule_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='date_released',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
