# Generated by Django 6.0.3 on 2026-05-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_oldloan_oldloanpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldloanpayment',
            name='old_loan',
        ),
        migrations.DeleteModel(
            name='OldLoan',
        ),
        migrations.DeleteModel(
            name='OldLoanPayment',
        ),
    ]
