# Generated by Django 6.0.3 on 2026-05-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_otherloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherLoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('other_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.otherloan')),
            ],
        ),
    ]
