# Generated by Django 6.0.3 on 2026-05-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_otherloanpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherloanpayment',
            name='other_loan',
        ),
        migrations.DeleteModel(
            name='OtherLoan',
        ),
        migrations.DeleteModel(
            name='OtherLoanPayment',
        ),
    ]
