# Generated by Django 6.0.3 on 2026-05-22 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_remove_otherloanpayment_other_loan_delete_otherloan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
